command: python3 /mlsteam/lab/darknet_wrapper.py
params:
  backup: /mlsteam/data/output/model_weights/trained
  batch: 64
  learning_rate: 0.001
  max_batches: 500
  repeat: 0
  scales: .1; .1
  steps: 400; 450
  subdivisions: 16
  train_dir: /mlsteam/data/yolo/training_data/yolo/images
  version: tiny
  weights_file: ''
params_definition:
  version:
    options:
    - tiny
    - original
